### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [whymesnoopy/prj-rev-bwfs-dasmoto#6]
**GRADE**: Needs Improvement

**SUMMARY**: Good start on this project. The site looks great but there is still a little bit of work to be done behind the scenes to make everything perfect.

It is very important to keep both the project folder and the code as neat as possible. In general, avoid leaving in anything that is unused or unnecessary as that can only lead to confusion and frustration down the line. In your code, keep your indentation and spacing consistent to yield code that is clean and easy to read. Also, try to always keep in mind DRY principles as you set your styling. Avoid repeating the same styling many times for similarly styled elements wherever possible. 

As a next step, try to straighten up the code and files for this project. Keeping things neat behind the scenes is arguably more important than getting the site to look exactly how you want it.

Have fun and keep up the good work!

**Comment by whymesnoopy** [comment]
Thanks for the review. I will work harder to pay attention to the details of organization when composing the html.  I'm enjoying the challenge and the course so far!
